<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="NC003" name="DemoMaven.Tests.DashBoard.LipidTests" tests="10" failures="1" timestamp="26 Apr 2019 09:27:13 GMT" time="45.626" errors="1">
  <testcase name="check" time="0.704" classname="DemoMaven.Tests.DashBoard.LipidTests">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at DemoMaven.Utilities.SuiteBase.captureFailureScreen(SuiteBase.java:128)
at DemoMaven.Tests.DashBoard.LipidTests.check(LipidTests.java:213)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- check -->
  <testcase name="VerifyValidLogin" time="12.586" classname="DemoMaven.Tests.DashBoard.LipidTests"/>
  <testcase name="TC_verifySelectPractice" time="12.444" classname="DemoMaven.Tests.DashBoard.LipidTests"/>
  <testcase name="verifyNavigateToLipid" time="10.822" classname="DemoMaven.Tests.DashBoard.LipidTests"/>
  <testcase name="verify2018BothAllAll" time="9.070" classname="DemoMaven.Tests.DashBoard.LipidTests">
    <failure type="java.lang.AssertionError" message="Records are not matching expected [1001] but found [36]">
      <![CDATA[java.lang.AssertionError: Records are not matching expected [1001] but found [36]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at DemoMaven.CommonActions.CommonAction.CommonAction.verifyAssertEqual(CommonAction.java:145)
at DemoMaven.Tests.DashBoard.LipidTests.verify2018BothAllAll(LipidTests.java:197)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify2018BothAllAll -->
  <testcase name="verify2018BothAllAll" time="0.000" classname="DemoMaven.Tests.DashBoard.LipidTests">
    <skipped/>
  </testcase> <!-- verify2018BothAllAll -->
  <testcase name="verify2018BothAllAll" time="0.000" classname="DemoMaven.Tests.DashBoard.LipidTests">
    <skipped/>
  </testcase> <!-- verify2018BothAllAll -->
  <testcase name="verify2018BothAllAll" time="0.000" classname="DemoMaven.Tests.DashBoard.LipidTests">
    <skipped/>
  </testcase> <!-- verify2018BothAllAll -->
  <testcase name="verify2018BothAllAll" time="0.000" classname="DemoMaven.Tests.DashBoard.LipidTests">
    <skipped/>
  </testcase> <!-- verify2018BothAllAll -->
  <testcase name="verify2018BothAllAll" time="0.000" classname="DemoMaven.Tests.DashBoard.LipidTests">
    <skipped/>
  </testcase> <!-- verify2018BothAllAll -->
</testsuite> <!-- DemoMaven.Tests.DashBoard.LipidTests -->
